import "@/styles/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NextAuthProvider from "./providers";
import NavBar from "@components/NavBar";
import { ReduxProvider } from "@/redux/provider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={inter.className}>
        <NextAuthProvider>
          <NavBar />
          <ReduxProvider>
            <main className="w-11/12 mx-auto mt-10">{children}</main>
          </ReduxProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
